secrete: "zzdivxat!`" # 服务端密钥，很重要务必在使用前更改
loglevel: "info" # 日志打印等级
serverIp: "101.34.166.251" # 服务端运行监听ip
serverPort: "81" # 服务端运行端口
autoReleaseTimeOut: 600000 # 客户端自动断开时间（毫秒）

clientServiceDescriptions: # 注册服务
  - serviceName: "qw607"
    serviceIp: "qw607.com"
    servicePort: "80"
    serviceEnable: false

manageConfig: # 管理端api服务
  managementApiPort: 777 #管理api端口
  useSsl: false # 是否使用ssl
  jksPath: "C:\\Users\\liuqiwei\\Desktop\\qw607.com_jks\\qw607.com.jks" #jks 证书地址
  jksPass: "3unpdl4r1rdkg3o" # jks 证书密码
  loginName: "xxx" # 登录用户名
  loginPassWord: "xxx" # 登录密码
  adminEnable: false # 是否启动静态页面