spring:
  datasource:
    druid:
      read:
        validation-query: "select 1"
        test-while-idle: true
        min-evictable-idle-time-millis: 130000
        time-between-eviction-runs-millis: 30000
        max-wait: 60000
        connection-properties: "druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500"
        filters: "stat,wall"
        max-active: 20
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://nuc:3306/jndc-server?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&connectTimeout=300000&socketTimeout=300000"
        type: com.alibaba.druid.pool.DruidDataSource
        username: "root"
        password: "wdwdwd"
        initial-size: 1
      write:
        validation-query: "select 1"
        test-while-idle: true
        min-evictable-idle-time-millis: 130000
        time-between-eviction-runs-millis: 30000
        max-wait: 60000
        connection-properties: "druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500"
        filters: "stat,wall"
        max-active: 50
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://nuc:3306/jndc-server?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&connectTimeout=300000&socketTimeout=300000"
        type: com.alibaba.druid.pool.DruidDataSource
        username: "root"
        password: "wdwdwd"
        initial-size: 1
  data:
    redis:
      lettuce:
        pool:
          max-active: 8
          max-wait: 5000 #最大等待时间
          max-idle: 8
          min-idle: 1
        timeout: 10000
      database: 0
      host: "nuc"
      password: "qAkctTgqsQVRwkKmy0"  #密码
      port: 6379
      client-type: lettuce

ndc:
  server:
    port: 8888


# mybatis-plus 打印sql
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

