spring:
  datasource:
    url: "jdbc:mysql://172.28.244.232:3306/senior-buyer?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai"
    username: "root"
    password: "wdwdwd"
    driver-class-name: com.mysql.cj.jdbc.Driver




