server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: "jndc-server"
  profiles:
    active: "h2" # h2/mysql


management:
  endpoints:
    web:
      exposure:
        include: '*'




#打印sql
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
