server:
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null
  application:
    name: "fll-server"
  profiles:
    #active: "mysql"
    active: "h2"


management:
  endpoints:
    web:
      exposure:
        include: '*'

snowflake:
  worker-id: 1
  data-center-id: 1

#------------------------Sa-Token 配置--------------------------------
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 3600
  # jwt秘钥
  jwt-secret-key: ogndsfgjwgmlkemtrekwngviewjvremtrewfwe
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 是否从cookie中读取token
  is-read-cookie: false

#打印sql
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

wechat:
  appid: "wx55bd507c852abae2"
  secret: "ca65d4be7a679430b59d975ac6a6090e"
