spring:
  flyway:
    enabled: true
    locations: classpath:db/mysql
  datasource:
    druid:
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
      write:
        validation-query: "select 1"
        test-while-idle: true
        min-evictable-idle-time-millis: 130000
        time-between-eviction-runs-millis: 30000
        max-wait: 60000
        connection-properties: "druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500"
        filters: "stat,wall"
        max-active: 50
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: "jdbc:mysql://192.168.0.114:3306/fll-server?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&connectTimeout=300000&socketTimeout=300000"
        type: com.alibaba.druid.pool.DruidDataSource
        username: "root"
        password: "wdwdwd"
        initial-size: 1
